const mongoose = require("mongoose");

// Declare the Schema of the Mongo model
var coinmaketcapCryptoSchema = new mongoose.Schema({
  name: { type: String },
  queryName: { type: String },
  code: { type: String },
  price: {
    usd: { type: String },
    btc: { type: String },
    eth: { type: String },
  },
  roi: { type: String },
  marketRank: { type: String },
  marketCap: {
    usd: { type: String },
    btc: { type: String },
    eth: { type: String },
    bnb: { type: String },
  },
  a24hourVolume: {
    usd: { type: String },
    self_code: { type: String },
    btc: { type: String },
    eth: { type: String },
    bnb: { type: String },
  },
  circulatingSupply: { type: String },
  totalSupply: { type: String },
  maxSupply: { type: String },
  allTimeHigh: { type: String },
  allTimeLow: { type: String },
  a52weekHigh: { type: String },
  a52weekLow: { type: String },
  a90dayHigh: { type: String },
  a90dayLow: { type: String },
  a30dayHigh: { type: String },
  a30dayLow: { type: String },
  a7dayHigh: { type: String },
  a7dayLow: { type: String },
  a24hourHigh: { type: String },
  a24hourLow: { type: String },
  yesterdaysHigh: { type: String },
  yesterdaysLow: { type: String },
  yesterdaysOpen: { type: String },
  yesterdaysClose: { type: String },
  yesterdaysChange: { type: String },
  yesterdaysVolume: { type: String },
  website: [{ type: String }],
  announcement: [{ type: String }],
  explorer: [{ type: String }],
  message_board: [{ type: String }],
  chat: [{ type: String }],
  sourceCode: [{ type: String }],
  technicalDocumentation: [{ type: String }],
  tags: [{ type: String }],
  icon: { type: String },
  report: {
    heading: { type: String },
    report_list: [{ type: String }],
    paragraph: { type: String },
    score: { type: String },
    updated_at: { type: String },
    market_opportunity: { type: String },
    underlying_technology: { type: String },
    ecosystem_structure: { type: String },
    core_team: { type: String },
    token_economics: { type: String },
    token_performance: { type: String },
    roadmap_progress: { type: String },
  },
  tokenInsightRating: {
    score: { type: String },
    score_string: { type: String },
    industry: { type: String },
    rating_description: { type: String },
  },
  dynamicPerformanceScore: { type: String },
  fcasRatingInitial: { type: String },
  fcasScore: { type: String },
  article: {
    heading1: { type: String },
    paragraph1: [{ type: String }],
    heading2: { type: String },
    paragraph2: [{ type: String }],
    heading3: { type: String },
    paragraph3: [{ type: String }],
    heading4: { type: String },
    paragraph4: [{ type: String }],
    heading5: { type: String },
    paragraph5: [{ type: String }],
    heading6: { type: String },
    paragraph6: [{ type: String }],
    heading7: { type: String },
    paragraph7: [{ type: String }],
    heading8: { type: String },
    paragraph8: [{ type: String }],
    heading9: { type: String },
    paragraph9: [{ type: String }],
    heading10: { type: String },
    paragraph10: [{ type: String }],
  },
});

//Export the model
const CoinMarketCapCrypto = mongoose.model(
  "CoinMarketCapCrypto",
  coinmaketcapCryptoSchema
);

var array = [
  {
    name: "Bitcoin",
    queryName: "Bitcoin",
    code: "BTC",
    price: {
      usd: "10,763.87",
      btc: "1.00000000",
      eth: "",
    },
    roi: "7,855.56",
    marketRank: "1",
    marketCap: {
      usd: "199,165,578,914",
      btc: "18,503,156",
      eth: "",
      bnb: "",
    },
    a24hourVolume: {
      usd: "58,506,660,879",
      self_code: "5,435,467",
      btc: "5,435,467",
      eth: "",
      bnb: "",
    },
    circulatingSupply: "18,503,156",
    totalSupply: "18,503,156",
    maxSupply: "21,000,000",
    allTimeHigh: "20,089.00",
    allTimeLow: "65.53",
    a52weekHigh: "12,359.06",
    a52weekLow: "4,106.98",
    a90dayHigh: "12,359.06",
    a90dayLow: "10,682.21",
    a30dayHigh: "10,945.35",
    a30dayLow: "10,682.21",
    a7dayHigh: "10,945.35",
    a7dayLow: "10,682.21",
    a24hourHigh: "10,798.86",
    a24hourLow: "10,682.21",
    yesterdaysHigh: "10,949.12",
    yesterdaysLow: "10,716.68",
    yesterdaysOpen: "10,771.64",
    yesterdaysClose: "10,721.33",
    yesterdaysChange: "-50.31",
    yesterdaysVolume: "22,720,365,389",
    website: ["https://bitcoin.org/"],
    announcement: [],
    explorer: [
      "https://blockchain.coinmarketcap.com/chain/bitcoin",
      "https://blockchain.info/",
      "https://live.blockcypher.com/btc/",
      "https://blockchair.com/bitcoin",
      "https://explorer.viabtc.com/btc",
    ],
    message_board: ["https://bitcointalk.org/"],
    chat: [],
    sourceCode: ["https://github.com/bitcoin/"],
    technicalDocumentation: ["https://bitcoin.org/bitcoin.pdf"],
    tags: [
      "Coin",
      "Mineable",
      "PoW",
      "SHA-256",
      "Store of Value",
      "State channels",
    ],
    icon: "https://s2.coinmarketcap.com/static/img/coins/32x32/1.png",
    report: {
      heading: "Bitcoin Report Highlights",
      report_list: [
        "Massive market dominance",
        "Traded virtually everywhere crypto is traded",
        "Global ecosystem and brand recognition",
        "Active core and third-party development",
        "Primary on- and off-ramp to fiat currencies",
      ],
      paragraph:
        "While institutional interest in Bitcoin as a store-of-value continues to grow, other tokens have become more suited to payments. Despite this, Bitcoin’s massive market dominance makes it unlikely that it will be usurped as the undisputed crypto heavyweight champion anytime soon.",
      score: "A-",
      updated_at: "Jun 3, 2019",
      market_opportunity: "9.8",
      underlying_technology: "8.3",
      ecosystem_structure: "9.5",
      core_team: "8.0",
      token_economics: "8.2",
      token_performance: "8.4",
      roadmap_progress: "6.7",
    },
    tokenInsightRating: {
      score: "AA",
      score_string: "Stable Outlook",
      industry: "General Payment Token",
      rating_description:
        "TokenInsight ratings follow a specialized rating system (where AAA is the highest rating) to represent the quality and risk of Cryptocurrency projects based on Team, Project, and Ecosystem metrics.",
    },
    dynamicPerformanceScore: "81.73",
    fcasRatingInitial: "A",
    fcasScore: "892",
    article: {
      heading1: "What Is Bitcoin (BTC)?",
      paragraph1: [
        "Bitcoin is a decentralized cryptocurrency originally described in a 2008 whitepaper by a person, or group of people, using the alias Satoshi Nakamoto. It was launched soon after, in January 2009.",
        "Bitcoin is a peer-to-peer online currency, meaning that all transactions happen directly between equal, independent network participants, without the need for any intermediary to permit or facilitate them. Bitcoin was created, according to Nakamoto’s own words, to allow “online payments to be sent directly from one party to another without going through a financial institution.”",
        "Some concepts for a similar type of a decentralized electronic currency precede BTC, but Bitcoin holds the distinction of being the first-ever cryptocurrency to come into actual use.",
      ],
      heading2: "Who Are The Founders Of Bitcoin?",
      paragraph2: [
        "Bitcoin’s original inventor is known under a pseudonym, Satoshi Nakamoto. As of 2020, the true identity of the person — or organization — that is behind the alias remains unknown.",
        "On October 31, 2008, Nakamoto published Bitcoin’s whitepaper, which described in detail how a peer-to-peer, online currency could be implemented. They proposed to use a decentralized ledger of transactions packaged in batches (called “blocks”) and secured by cryptographic algorithms — the whole system would later be dubbed “blockchain.”",
        "Just two months later, on January 3, 2009, Nakamoto mined the first block on the Bitcoin network, known as the genesis block, thus launching the world’s first cryptocurrency.",
        "However, while Nakamoto was the original inventor of Bitcoin, as well as the author of its very first implementation, over the years a large number of people have contributed to improving the cryptocurrency’s software by patching vulnerabilities and adding new features.",
        "Bitcoin’s source code repository on GitHub lists more than 750 contributors, with some of the key ones being Wladimir J. van der Laan, Marco Falke, Pieter Wuille, Gavin Andresen, Jonas Schnelli and others.",
      ],
      heading3: "What Makes Bitcoin Unique?",
      paragraph3: [
        "Bitcoin’s most unique advantage comes from the fact that it was the very first cryptocurrency to appear on the market.",
        "It has managed to create a global community and give birth to an entirely new industry of millions of enthusiasts who create, invest in, trade and use Bitcoin and other cryptocurrencies in their everyday lives. The emergence of the first cryptocurrency has created a conceptual and technological basis that subsequently inspired the development of thousands of competing projects.",
        "The entire cryptocurrency industry — now worth more than $300 billion — is based on the idea realized by Bitcoin: money that can be sent and received by anyone, anywhere in the world without reliance on trusted intermediaries, such as banks and financial services companies.",
        "Thanks to its pioneering nature, BTC remains at the top of this energetic market after over a decade of existence. Even after Bitcoin has lost its undisputed dominance, it remains the largest cryptocurrency, with a market capitalization that fluctuated between $100-$200 billion in 2020, owing in large part to the ubiquitousness of platforms that provide use-cases for BTC: wallets, exchanges, payment services, online games and more.",
      ],
      heading4: "Related Pages:",
      paragraph4: [
        "Looking for market and blockchain data for BTC? Visit our block explorer.",
        "Want to buy Bitcoin? Use CoinMarketCap’s guide.",
      ],
      heading5: "How Much Bitcoin Is In Circulation?",
      paragraph5: [
        "Bitcoin’s total supply is limited by its software and will never exceed 21,000,000 coins. New coins are created during the process known as “mining”: as transactions are relayed across the network, they get picked up by miners and packaged into blocks, which are in turn protected by complex cryptographic calculations.",
        "As compensation for spending their computational resources, the miners receive rewards for every block that they successfully add to the blockchain. At the moment of Bitcoin’s launch, the reward was 50 bitcoins per block: this number gets halved with every 210,000 new blocks mined — which takes the network roughly four years. As of 2020, the block reward has been halved three times and comprises 6.25 bitcoins.",
        "Bitcoin has not been premined, meaning that no coins have been mined and/or distributed between the founders before it became available to the public. However, during the first few years of BTC’s existence, the competition between miners was relatively low, allowing the earliest network participants to accumulate significant amounts of coins via regular mining: Satoshi Nakamoto alone is believed to own over a million Bitcoin.",
      ],
      heading6: "How Is the Bitcoin Network Secured?",
      paragraph6: [
        "Bitcoin is secured with the SHA-256 algorithm, which belongs to the SHA-2 family of hashing algorithms, which is also used by its fork Bitcoin Cash (BCH), as well as several other cryptocurrencies.",
      ],
      heading7: "Where Can You Buy [Bitcoin] ([BTC])?",
      paragraph7: [
        "Bitcoin is, in many regards, almost synonymous with cryptocurrency, which means that you can buy or sell it on virtually every crypto exchange — both for fiat money and other cryptocurrencies. Some of the main markets where BTC trading is available are:",
        "Binance",
        "Coinbase Pro",
        "OKEx",
        "Kraken",
        "Huobi Global",
        "Bitfinex",
        "If you are new to crypto, use CoinMarketCap’s own easy guide to buying Bitcoin.",
      ],
      heading8: "",
      paragraph8: [],
      heading9: "",
      paragraph9: [],
      heading10: "",
      paragraph10: [],
    },
  },
  {
    name: "Ethereum",
    queryName: "Ethereum",
    code: "ETH",
    price: {
      usd: "358.79",
      btc: "0.03327610",
      eth: "",
    },
    roi: "9000",
    marketRank: "2",
    marketCap: {
      usd: "40,499,412,753",
      btc: "3,754,185",
      eth: "",
      bnb: "",
    },
    a24hourVolume: {
      usd: "13,804,428,060",
      self_code: "38,451,081",
      btc: "1,279,633",
      eth: "",
      bnb: "",
    },
    circulatingSupply: "112,801,157",
    totalSupply: "112,801,157",
    maxSupply: "",
    allTimeHigh: "1,432.88",
    allTimeLow: "0.420897",
    a52weekHigh: "487.21",
    a52weekLow: "95.18",
    a90dayHigh: "487.21",
    a90dayLow: "352.15",
    a30dayHigh: "487.21",
    a30dayLow: "352.15",
    a7dayHigh: "366.43",
    a7dayLow: "352.15",
    a24hourHigh: "359.04",
    a24hourLow: "352.15",
    yesterdaysHigh: "366.89",
    yesterdaysLow: "354.83",
    yesterdaysOpen: "357.31",
    yesterdaysClose: "354.95",
    yesterdaysChange: "-2.36",
    yesterdaysVolume: "12,102,509,266",
    website: ["https://www.ethereum.org/"],
    announcement: ["https://bitcointalk.org/index.php?topic=428589.0"],
    explorer: [
      "https://blockchain.coinmarketcap.com/chain/ethereum",
      "https://etherscan.io/",
      "https://ethplorer.io/",
      "https://blockchair.com/ethereum",
      "https://eth.tokenview.com/en/blocklist",
    ],
    message_board: ["https://forum.ethereum.org/"],
    chat: ["https://gitter.im/orgs/ethereum/rooms"],
    sourceCode: ["https://github.com/ethereum"],
    technicalDocumentation: [
      "https://github.com/ethereum/wiki/wiki/White-Paper",
    ],
    tags: ["Coin", "Mineable", "PoW", "Smart Contracts", "Binance Chain"],
    icon: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    report: {
      heading: "Ethereum Report Highlights",
      report_list: [
        "Phase 0 of Ethereum 2.0 upgrade as expected around Q2 2020",
        "Phase 0 will feature an entirely new chain, which will operate on Proof of Stake (PoS)",
        "The capital locked up in DeFi smart contracts has grown from zero to nearly $1B",
        "Ethereum browser wallet, Metamask, has recently surpassed one million users",
        "Ethereum Foundation has around $100M to support the ecosystem",
      ],
      paragraph:
        "Ethereum is fundamentally stronger than it's ever been. Despite all of the criticism it continues to be the number one project by development activity, with a massive developer community. The project is in a good position to not only maintain its spot as the number one platform for smart contracts, but grow its dominance in the coming quarter.",
      score: "B+",
      updated_at: "Feb 28, 2020",
      market_opportunity: "9.0",
      underlying_technology: "7.5",
      ecosystem_structure: "9.5",
      core_team: "8.0",
      token_economics: "8.0",
      token_performance: "6.5",
      roadmap_progress: "6.5",
    },
    tokenInsightRating: {
      score: "A",
      score_string: "Stable Outlook",
      industry: "Smart Contract Platform",
      rating_description:
        "TokenInsight ratings follow a specialized rating system (where AAA is the highest rating) to represent the quality and risk of Cryptocurrency projects based on Team, Project, and Ecosystem metrics.",
    },
    dynamicPerformanceScore: "71.54",
    fcasRatingInitial: "S",
    fcasScore: "971",
    article: {
      heading1: "What Is Ethereum (ETH)?",
      paragraph1: [
        "Ethereum is a decentralized open-source blockchain system that features its own cryptocurrency, Ether. ETH works as a platform for numerous other cryptocurrencies, as well as for the execution of decentralized smart contracts.",
        "Ethereum was first described in a 2013 white paper by Vitalik Buterin. Buterin, along with other co-founders, secured funding for the project in an online public crowd sale in the summer of 2014 and officially launched the blockchain on July 30, 2015.",
        "Ethereum’s own purported goal is to become a global platform for decentralized applications, allowing users from all over the world to write and run software that is resistant to censorship, downtime, and fraud.",
      ],
      heading2: "Who Are the Founders of Ethereum?",
      paragraph2: [
        "Ethereum has a total of eight co-founders — an unusually large number for a crypto project. They first met on June 7, 2014, in Zug, Switzerland.",
        "Russian-Canadian Vitalik Buterin is perhaps the best known of the bunch. He authored the original white paper that first described Ethereum in 2013 and still works on improving the platform to this day. Prior to ETH, Buterin co-founded and wrote for the Bitcoin Magazine news website.",
        "British programmer Gavin Wood is arguably the second most important co-founder of ETH, as he coded the first technical implementation of Ethereum in the C++ programming language, proposed Ethereum’s native programming language Solidity and was the first chief technology officer of the Ethereum Foundation. Before Ethereum, Wood was a research scientist at Microsoft. Afterward, he moved on to establish the Web3 Foundation.",
        "Among the other co-founders of Ethereum are: - Anthony Di Iorio, who underwrote the project during its early stage of development. - Charles Hoskinson, who played the principal role in establishing the Swiss-based Ethereum Foundation and its legal framework. - Mihai Alisie, who provided assistance in establishing the Ethereum Foundation. - Joseph Lubin, a Canadian entrepreneur, who, like Di Iorio, has helped fund Ethereum during its early days, and later founded an incubator for startups based on ETH called ConsenSys. - Amir Chetrit, who helped co-found Ethereum but stepped away from it early into the development.",
      ],
      heading3: "What Makes Ethereum Unique?",
      paragraph3: [
        "Ethereum has pioneered the concept of a blockchain smart contract platform. Smart contracts are computer programs that automatically execute the actions necessary to fulfill an agreement between several parties on the internet. They were designed to reduce the need for trusted intermediates between contractors, thus reducing transaction costs while also increasing transaction reliability.",
        "Ethereum’s principal innovation was designing a platform that allowed it to execute smart contracts using the blockchain, which further reinforces the already existing benefits of smart contract technology. Ethereum’s blockchain was designed, according to co-founder Gavin Wood, as a sort of “one computer for the entire planet,” theoretically able to make any program more robust, censorship-resistant and less prone to fraud by running it on a globally distributed network of public nodes.",
        "In addition to smart contracts, Ethereum’s blockchain is able to host other cryptocurrencies, called “tokens,” through the use of its ERC-20 compatibility standard. In fact, this has been the most common use for the ETH platform so far: to date, more than 280,000 ERC-20-compliant tokens have been launched. Over 40 of these make the top-100 cryptocurrencies by market capitalization, for example, USDT, LINK and BNB.",
        "B: Related Pages:",
        "New to crypto? Learn how to buy Bitcoin today.",
        "Ready to learn more? Visit our learning hub.",
        "Want to look up a transaction? Visit our block explorer.",
        "Curious about the crypto space? Read our blog!",
      ],
      heading4: "How Many Ethereum (ETH) Coins Are There In Circulation?",
      paragraph4: [
        "In August 2020, there were around 112 million ETH coins in circulation, 72 million of which were issued in the genesis block — the first ever block on the Ethereum blockchain. Of these 72 million, 60 million were allocated to the initial contributors to the 2014 crowd sale that funded the project, and 12 million were given to the development fund.",
        "The remaining amount has been issued in the form of block rewards to the miners on the Ethereum network. The original reward in 2015 was 5 ETH per block, which later went down to 3 ETH in late 2017 and then to 2 ETH in early 2019. The average time it takes to mine an Ethereum block is around 13-15 seconds.",
        "One of the major differences between Bitcoin and Ethereum’s economics is that the latter is not deflationary, i.e. its total supply is not limited. Ethereum’s developers justify this by not wanting to have a “fixed security budget” for the network. Being able to adjust ETH’s issuance rate via consensus allows the network to maintain the minimum issuance needed for adequate security.",
      ],
      heading5: "How Is the Ethereum Network Secured?",
      paragraph5: [
        "As of August 2020, Ethereum is secured via the Ethash proof-of-work algorithm, belonging to the Keccak family of hash functions.",
        "There are plans, however, to transition the network to a proof-of-stake algorithm tied to the major Ethereum 2.0 update, slated to launch in late 2020 or early 2021.",
      ],
      heading6: "Where Can You Buy Ethereum (ETH)?",
      paragraph6: [
        "Given the fact that Ethereum is the second-largest cryptocurrency after Bitcoin, ETH trading pairs are listed on nearly all of the major crypto exchanges. Some of the largest markets include:",
        "Binance",
        "Coinbase Pro",
        "OKEx",
        "Kraken",
        "Huobi Global",
      ],
      heading7: "",
      paragraph7: [],
      heading8: "",
      paragraph8: [],
      heading9: "",
      paragraph9: [],
      heading10: "",
      paragraph10: [],
    },
  },
  {
    name: "Tether",
    queryName: "Tether",
    code: "USDT",
    price: {
      usd: "1.00",
      btc: "0.00009302",
      eth: "0.00279448",
    },
    roi: "0.16",
    marketRank: "3",
    marketCap: {
      usd: "15,485,390,442",
      btc: "1,438,092",
      eth: "43,204,192",
      bnb: "",
    },
    a24hourVolume: {
      usd: "39,867,303,180",
      self_code: "39,816,939,845",
      btc: "3,703,339",
      eth: "111,513,800",
      bnb: "",
    },
    circulatingSupply: "15,460,539,837",
    totalSupply: "15,876,284,578",
    maxSupply: "",
    allTimeHigh: "1.21",
    allTimeLow: "0",
    a52weekHigh: "1.08",
    a52weekLow: "0.899490",
    a90dayHigh: "1.06",
    a90dayLow: "1.00",
    a30dayHigh: "1.00",
    a30dayLow: "1.00",
    a7dayHigh: "1.00",
    a7dayLow: "1.00",
    a24hourHigh: "1.00",
    a24hourLow: "1.00",
    yesterdaysHigh: "1.01",
    yesterdaysLow: "0.996960",
    yesterdaysOpen: "1.00",
    yesterdaysClose: "1.00",
    yesterdaysChange: "0.001854",
    yesterdaysVolume: "35,171,797,337",
    website: ["https://tether.to/"],
    announcement: [],
    explorer: [
      "https://www.omniexplorer.info/asset/31",
      "https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7",
      "https://usdt.tokenview.com/",
      "https://tronscan.org/#/token20/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
      "https://blockchair.com/ethereum/erc-20/token/0xdac17f958d2ee523a2206206994597c13d831ec7",
    ],
    message_board: [],
    chat: [],
    sourceCode: [],
    technicalDocumentation: [
      "https://tether.to/wp-content/uploads/2016/06/TetherWhitePaper.pdf",
    ],
    tags: [
      "Token",
      "Store of Value",
      "Payment",
      "Stablecoin",
      "Stablecoin - Asset-Backed",
    ],
    icon: "https://s2.coinmarketcap.com/static/img/coins/64x64/825.png",
    report: {
      heading: "",
      report_list: [],
      paragraph: "",
      score: "",
      updated_at: "",
      market_opportunity: "",
      underlying_technology: "",
      ecosystem_structure: "",
      core_team: "",
      token_economics: "",
      token_performance: "",
      roadmap_progress: "",
    },
    tokenInsightRating: {
      score: "B",
      score_string: "Developing Watch",
      industry: "General Payment Token",
      rating_description:
        "TokenInsight ratings follow a specialized rating system (where AAA is the highest rating) to represent the quality and risk of Cryptocurrency projects based on Team, Project, and Ecosystem metrics.",
    },
    dynamicPerformanceScore: "71.5",
    fcasRatingInitial: "A",
    fcasScore: "780",
    article: {
      heading1: "What Is Tether (USDT)?",
      paragraph1: [
        "USDT is a stablecoin (stable-value cryptocurrency) that mirrors the price of the U.S. dollar, issued by a Hong Kong-based company Tether. The token’s peg to the USD is achieved via maintaining a sum of dollars in reserves that is equal to the number of USDT in circulation.",
        "Originally launched in July 2014 as Realcoin, a second-layer cryptocurrency token built on top of Bitcoin’s blockchain through the use of the Omni platform, it was later renamed to USTether, and then, finally, to USDT. In addition to Bitcoin’s, USDT was later updated to work on the Ethereum, EOS, Tron, Algorand, SLP and OMG blockchains.",
        "The stated purpose of USDT is to combine the unrestricted nature of cryptocurrencies — which can be sent between users without a trusted third-party intermediary — with the stable value of the US dollar.",
      ],
      heading2: "Who Are The Founders Of Tether?",
      paragraph2: [
        "USDT — or as it was known at the time, Realcoin — was launched in 2014 by Brock Pierce, Reeve Collins and Craig Sellars.",
        "Brock Pierce is a well-known entrepreneur who has co-founded a number of high-profile projects in the crypto and entertainment industries. In 2013, he co-founded a venture capital firm Blockchain Capital, which by 2017 had raised over $80 million in funding. In 2014, Pierce became the director of the Bitcoin Foundation, a nonprofit established to help improve and promote Bitcoin. Pierce has also co-founded Block.one, the company behind EOS, one of the largest cryptocurrencies on the market.",
        "Reeve Collins was the CEO of Tether for the first two years of its existence. Prior to that, he had co-founded several successful companies, such as the online ad network Traffic Marketplace, entertainment studio RedLever and gambling website Pala Interactive. As of 2020, Collins is heading SmarMedia Technologies, a marketing and advertising tech company.",
        "Other than working on Tether, Craig Sellars has been a member of the Omni Foundation for over six years. Its Omni Protocol allows users to create and trade smart-contract based properties and currencies on top of Bitcoin’s blockchain. Sellars has also worked in several other cryptocurrency companies and organizations, such as Bitfinex, Factom, Synereo and the MaidSafe Foundation.",
      ],
      heading3: "What Makes Tether Unique?",
      paragraph3: [
        "USDT’s unique feature is the fact that its value is guaranteed by Tether to remain pegged to the U.S. dollar. According to Tether, whenever it issues new USDT tokens, it allocates the same amount of USD to its reserves, thus ensuring that USDT is fully backed by cash and cash equivalents.",
        "The famously high volatility of the crypto markets means that cryptocurrencies can rise or fall by 10-20% within a single day, making them unreliable as a store of value. USDT, on the other hand, is protected from these fluctuations.",
        "This property makes USDT a safe haven for crypto investors: during periods of high volatility, they can park their portfolios in Tether without having to completely cash out into USD. In addition, USDT provides a simple way to transact a U.S. dollar equivalent between regions, countries and even continents via blockchain — without having to rely on a slow and expensive intermediary, like a bank or a financial services provider.",
        "However, over the years, there have been a number of controversies regarding the validity of Tether’s claims about their USD reserves, at times disrupting USDT’s price, which went down as low as $0.88 at one point in its history. Many have raised concerns about the fact that Tether’s reserves have never been fully audited by an independent third party.",
      ],
      heading4: "Related Pages:",
      paragraph4: [
        "Looking for market and blockchain data for BTC? Visit our block explorer.",
        "Want to buy crypto? Use CoinMarketCap’s guide.",
      ],
      heading5: "How Many Tether (USDT) Coins Are There In Circulation?",
      paragraph5: [
        "There is no hard-coded limit on the total supply of USDT — given the fact that it belongs to a private company, theoretically, its issuance is limited only by Tether’s own policies. However, because Tether claims that every single USDT is supposed to be backed by one U.S. dollar, the amount of tokens is limited by the company’s actual cash reserves.",
        "Moreover, Tether does not disclose its issuance schedules ahead of time. Instead, they provide daily transparency reports, listing the total amount of their asset reserves and liabilities, the latter corresponding to the amount of USDT in circulation.",
        "As of September 2020, there are over 14.4 billion USDT tokens in circulation, which are backed by $14.6 billion in assets, according to Tether.",
      ],
      heading6: "How Is the Tether Network Secured?",
      paragraph6: [
        "USDT does not have its own blockchain — instead, it operates as a second-layer token on top of other cryptocurrencies’ blockchains: Bitcoin, Ethereum, EOS, Tron, Algorand, Bitcoin Cash and OMG, and is secured by their respective hashing algorithms.",
      ],
      heading7: "Where Can You Buy Tether (USDT)?",
      paragraph7: [
        "USDT is available on a large number of cryptocurrency exchanges. In fact, USDT’s average daily trading volume is often on par or even exceeds that of Bitcoin. It is especially prominent on those exchanges where fiat-to-crypto trading pairs are unavailable, as it provides a viable alternative to USD. Here are some of the most popular exchanges that support Tether trading:",
        "Binance",
        "OKEx",
        "HitBTC",
        "Huobi Global",
      ],
      heading8: '',
      paragraph8: [],
      heading9: '',
      paragraph9: [],
      heading10: '',
      paragraph10: [],
    },
  },
];

CoinMarketCapCrypto.create(array).then((docs) => {
  console.log(docs);
});

// Connect MongoDB at default port 27017.
mongoose.connect(
  `mongodb+srv://${process.env.DB_USER}:${process.env.DB_PASSWORD}@cluster0-7slh6.mongodb.net/test?retryWrites=true&w=majority`,
  {
    useNewUrlParser: true,
    useCreateIndex: true,
  },
  (err) => {
    if (!err) {
      console.log("MongoDB Connection Succeeded.");
    } else {
      console.log("Error in DB connection: " + err);
    }
  }
);
