const mongoose = require("mongoose");

// Declare the Schema of the Mongo model
const coinmaketcapCryptoSchema = new mongoose.Schema({
  name: { type: String },
  queryName: { type: String },
  code: { type: String },
  price: {
    usd: { type: String },
    btc: { type: String },
    eth: { type: String },
  },
  roi: { type: String },
  marketRank: { type: String },
  marketCap: {
    usd: { type: String },
    btc: { type: String },
    eth: { type: String },
    bnb: { type: String },
  },
  a24hourVolume: {
    usd: { type: String },
    self_code: { type: String },
    btc: { type: String },
    eth: { type: String },
    bnb: { type: String },
  },
  circulatingSupply: { type: String },
  totalSupply: { type: String },
  maxSupply: { type: String },
  allTimeHigh: { type: String },
  allTimeLow: { type: String },
  a52weekHigh: { type: String },
  a52weekLow: { type: String },
  a90dayHigh: { type: String },
  a90dayLow: { type: String },
  a30dayHigh: { type: String },
  a30dayLow: { type: String },
  a7dayHigh: { type: String },
  a7dayLow: { type: String },
  a24hourHigh: { type: String },
  a24hourLow: { type: String },
  yesterdaysHigh: { type: String },
  yesterdaysLow: { type: String },
  yesterdaysOpen: { type: String },
  yesterdaysClose: { type: String },
  yesterdaysChange: { type: String },
  yesterdaysVolume: { type: String },
  website: [{ type: String }],
  announcement: [{ type: String }],
  explorer: [{ type: String }],
  message_board: [{ type: String }],
  chat: [{ type: String }],
  sourceCode: [{ type: String }],
  technicalDocumentation: [{ type: String }],
  tags: [{ type: String }],
  icon: { type: String },
  report: {
    heading: { type: String },
    report_list: [{ type: String }],
    paragraph: { type: String },
    score: { type: String },
    updated_at: { type: String },
    market_opportunity: { type: String },
    underlying_technology: { type: String },
    ecosystem_structure: { type: String },
    core_team: { type: String },
    token_economics: { type: String },
    token_performance: { type: String },
    roadmap_progress: { type: String },
  },
  tokenInsightRating: {
    score: { type: String },
    score_string: { type: String },
    industry: { type: String },
    rating_description: { type: String },
  },
  dynamicPerformanceScore: { type: String },
  fcasRatingInitial: { type: String },
  fcasScore: { type: String },
  article: {
    heading1: { type: String },
    paragraph1: [{ type: String }],
    heading2: { type: String },
    paragraph2: [{ type: String }],
    heading3: { type: String },
    paragraph3: [{ type: String }],
    heading4: { type: String },
    paragraph4: [{ type: String }],
    heading5: { type: String },
    paragraph5: [{ type: String }],
    heading6: { type: String },
    paragraph6: [{ type: String }],
    heading7: { type: String },
    paragraph7: [{ type: String }],
    heading8: { type: String },
    paragraph8: [{ type: String }],
    heading9: { type: String },
    paragraph9: [{ type: String }],
    heading10: { type: String },
    paragraph10: [{ type: String }],
  },
});

//Export the model
module.exports = mongoose.model(
  "CoinMarketCapCrypto",
  coinmaketcapCryptoSchema
);
